### ISSUE TITLE
feat: album search

### ISSUE THREAD

**Issue by polarhive** [acmpesuecc/jukebox_hn6#1]
Right now, users need to manually input the album URL after visiting the artist's last.fm page, like so:

```sh
./jukebox -p: "<lastfm: playlist/album url>"
```

Deliverables:

- [ ] Implement a wizard-like menu (I suggest `fzf`) for album selection.
- [ ] Sub flag to automatically download all albums sequentially without manual input.

Ideas:

Implement some kind of helper-utils that scrapes lastfm (probably not the best idea to stick to pure bash).

**Comment by ManishMDharani** [comment]
can i get this issue assigned?

**Comment by polarhive** [comment]
!assign @ManishMDharani

**Comment by YVLNair** [comment]
Can I get this issue assigned?

**Comment by polarhive** [comment]
!assign @YVLNair

**Comment by polarhive** [comment]
!deassign

**Comment by ManishMDharani** [comment]
can i get this issue?

**Comment by polarhive** [comment]
@YVLNair @ManishMDharani any takers?
