### ISSUE TITLE
tests/bugs: funky characters in artist/title parameters causes the script to terminate

### ISSUE THREAD

**Issue by polarhive** [acmpesuecc/jukebox_hn6#2]
Write tests (use Python) to help run through some weird artist -- title combos and pass them as arguments to `jukebox` using `STDNIN`

**Comment by Hemaksh-b** [comment]
can i be assigned this

**Comment by polarhive** [comment]
!assign @Hemaksh-b

**Comment by Hemaksh-b** [comment]
i went for dinner :/

**Comment by polarhive** [comment]
!deassign

**Comment by polarhive** [comment]
@Hemaksh-b do you want to work on this?
