### ISSUE TITLE
feat/mix: listen-along

### ISSUE THREAD

**Issue by polarhive** [acmpesuecc/jukebox_hn6#3]
Loads `friends.txt` containing lastfm usernames and adds tracks to the MPD queue based on a similarity threshold between your music and your friends' music.

```sh
./jukebox -f 10
# 10% of your tracks would be your friend's and 90% yours
```

This should scale for how many ever friends in the textfile and make sure you test this while drafting your PR.

**Comment by RohanChirbi** [comment]
Can you please assign me to this problem?

**Comment by polarhive** [comment]
!assign @RohanChirbi

**Comment by polarhive** [comment]
@RohanChirbi do you want to work on this?
