### ISSUE TITLE
ext/psync: refactor to work with rsync instead of adb

### ISSUE THREAD

**Issue by polarhive** [acmpesuecc/jukebox_hn6#4]
Pick a FOSS rsync server (not via Termux). I found these two.

https://f-droid.org/en/packages/com.github.ktsr42.rsyncserver/
https://f-droid.org/en/packages/org.amoradi.syncopoli/

Update the docs and the `psync` helper script to use pure rsync and not over adb.

**Comment by polarhive** [comment]
> A Maintainer will review it soon!

![badsamosabot](https://c.tenor.com/HA2ennVsLV8AAAAC/tenor.gif)

**Comment by SavvyHex** [comment]
Hello, can I get assigned to this?

**Comment by polarhive** [comment]
!assign @SavvyHex

**Comment by polarhive** [comment]
!deassign

**Comment by polarhive** [comment]
@SavvyHex do you want to work on it?
